# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rugby', '0001_initial'),
        ('cricket', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketMonthlyView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_name', to='cricket.Tour')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sport_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='RugbyMonthlyView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Match')),
            ],
        ),
    ]
