# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_view', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricketmonthlyview',
            name='date',
        ),
    ]
