# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingdetail',
            name='bowled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowled_by', to='cricket.BowlingDetail'),
        ),
        migrations.AddField(
            model_name='battingdetail',
            name='caught_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caught_by', to='cricket.CricketPlayer'),
        ),
        migrations.AddField(
            model_name='bowlingdetail',
            name='bowled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowled', to='cricket.BattingDetail'),
        ),
    ]
