# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('cricket', '0002_auto_20171116_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tier_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.Tier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cricketplayer',
            name='domestic_teams',
            field=models.ManyToManyField(related_name='cricket_domestic_teams', to='sports.Team'),
        ),
        migrations.AlterField(
            model_name='cricketplayer',
            name='international_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cricket_international_team', to='sports.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cricket_away_team', to='sports.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cricket_home_team', to='sports.Team'),
        ),
    ]
