# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20171117_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallofWicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wicket', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('innings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innings_wickets', to='cricket.InningsScorecard')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wickets', to='cricket.Match')),
            ],
        ),
        migrations.AlterField(
            model_name='battingdetail',
            name='status',
            field=models.CharField(choices=[('not out', 'not out'), ('bowled', 'bowled'), ('caught', 'caught'), ('lbw', 'lbw'), ('stumped', 'stumped'), ('ran-out', 'ran-out'), ('retired-hurt', 'retired-hurt'), ('retired-out', 'retired-out'), ('timed-out', 'timed-out'), ('handled-the-ball', 'handled-the-ball')], default='not out', max_length=15),
        ),
    ]
