# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('articles', '0003_auto_20171106_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='post_slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='sports.Sport'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
