# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20171109_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headline_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
