# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_auto_20171115_1959'),
        ('articles', '0007_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='team_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='sports.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='team_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='sports.Team'),
            preserve_default=False,
        ),
    ]
