# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('sport_slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('category_slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport_Category'),
        ),
    ]
