# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('sport_slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('category_slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Gender')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Tier'),
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport_Category'),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport'),
        ),
        migrations.AddField(
            model_name='matchtype',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Tier'),
        ),
    ]
