# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('tier_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Tier')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rugby_away_team', to='sports.Team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rugby_home_team', to='sports.Team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchScorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.MatchScorecard')),
            ],
        ),
        migrations.CreateModel(
            name='RugbyPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('domestic_teams', models.ManyToManyField(related_name='rugby_domestic_teams', to='sports.Team')),
                ('international_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rugby_international_team', to='sports.Team')),
            ],
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.RugbyPlayer'),
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
        ),
    ]
