# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('rugby', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_date',
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='fixture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rugby.Match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='fixture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rugby.MatchScorecard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rugby.RugbyPlayer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerdetail',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
            preserve_default=False,
        ),
    ]
