# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0002_auto_20171118_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='bonus_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='drawn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='games_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='points_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='points_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='won',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
