# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('rugby', '0003_auto_20171118_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(blank=True, null=True)),
                ('won', models.IntegerField(blank=True, null=True)),
                ('drawn', models.IntegerField(blank=True, null=True)),
                ('lost', models.IntegerField(blank=True, null=True)),
                ('points_for', models.IntegerField(blank=True, null=True)),
                ('points_against', models.IntegerField(blank=True, null=True)),
                ('bonus_points', models.IntegerField(blank=True, null=True)),
                ('total_points', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='bonus_points',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='drawn',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='points_against',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='points_for',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='team',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='won',
        ),
        migrations.AddField(
            model_name='competitiondetail',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Competition'),
        ),
        migrations.AddField(
            model_name='competitiondetail',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
        ),
    ]
