# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0004_auto_20171118_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchscorecard',
            name='score',
        ),
        migrations.RemoveField(
            model_name='playerdetail',
            name='fixture',
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='squad',
            field=models.ManyToManyField(related_name='matchday_squad', to='rugby.PlayerDetail'),
        ),
    ]
